services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    network_mode: host

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    network_mode: host

  telegraf:
    image: telegraf:latest
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - timescaledb
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_PLUGINS_PREINSTALL=${GF_PLUGINS_PREINSTALL}
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: host

volumes:
  pgadmin_data:
  timescale_data:
  grafana-storage:
